//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (SkodaResxGenerator).
//     Runtime Version: 1.0.2013.2
//
//     This file is generated only once, so you can make your own changes.
//     When you delete this file from project, it will be generated again,
//	   but your personal changes in that fiel will be lost.
//
//     Generated code based on input file: C:\Users\Michal\Documents\Work\SkodaChristmas2015\SkodaChristmas2015\Resources\ChristmasDefault.resx
//     Generated code output file: C:\Users\Michal\Documents\Work\SkodaChristmas2015\SkodaChristmas2015\Resources\ChristmasDefault.Settings.cs
//     Timestamp: úterý 1. prosince 2015 14:16:44
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Resources.Skoda;

namespace SkodaChristmas2015.Resources
{
    /// <summary>
    ///  This is a settings class for resource <see cref="SkodaChristmas2015.Resources.ChristmasDefault"/>.
    ///  You can control AppGuid and ResourceNamespace properties
    ///  to achieve needed state and beahavior.
    /// </summary>
    internal partial class ChristmasDefaultSetting : ISkodaResuorceManagerSettings
    {
        /// <summary>
        ///  Return the GUID that represents this application at resource server.
        /// </summary>
        public string AppGuid
        {
            get { return "cc5743bd-c389-40a1-a27a-df571f6e240d"; }
        }

        /// <summary>
        ///  Return the Resource name that represents this resources at resource server.
        /// </summary>
        public string ResourceNamespace
        {
            get { return "ChristmasDefault"; }
        }

        /// <summary>
        ///  It have to return name of configuration section where is the SkodaResourceManagerSection.
        /// </summary>
        public string ConfigurationSectionName
        {
            get { return String.Empty; }
        }

    } // class
} // namespace
